// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leader_election.proto

/*
Package rproto is a generated protocol buffer package.

It is generated from these files:
	leader_election.proto

It has these top-level messages:
	VoteRequest
	VoteResult
	AppendEntryRequest
	AppendEntryResult
*/
package rproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteRequest struct {
	Term        uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId uint32 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId" json:"candidate_id,omitempty"`
}

func (m *VoteRequest) Reset()                    { *m = VoteRequest{} }
func (m *VoteRequest) String() string            { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()               {}
func (*VoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteRequest) GetCandidateId() uint32 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

type VoteResult struct {
	Term        uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted" json:"vote_granted,omitempty"`
}

func (m *VoteResult) Reset()                    { *m = VoteResult{} }
func (m *VoteResult) String() string            { return proto.CompactTextString(m) }
func (*VoteResult) ProtoMessage()               {}
func (*VoteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VoteResult) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *VoteResult) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntryRequest struct {
	Term uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
}

func (m *AppendEntryRequest) Reset()                    { *m = AppendEntryRequest{} }
func (m *AppendEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntryRequest) ProtoMessage()               {}
func (*AppendEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntryRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

type AppendEntryResult struct {
	Term    uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntryResult) Reset()                    { *m = AppendEntryResult{} }
func (m *AppendEntryResult) String() string            { return proto.CompactTextString(m) }
func (*AppendEntryResult) ProtoMessage()               {}
func (*AppendEntryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppendEntryResult) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*VoteRequest)(nil), "rproto.VoteRequest")
	proto.RegisterType((*VoteResult)(nil), "rproto.VoteResult")
	proto.RegisterType((*AppendEntryRequest)(nil), "rproto.AppendEntryRequest")
	proto.RegisterType((*AppendEntryResult)(nil), "rproto.AppendEntryResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LeaderElection service

type LeaderElectionClient interface {
	RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResult, error)
	AppendEntry(ctx context.Context, in *AppendEntryRequest, opts ...grpc.CallOption) (*AppendEntryResult, error)
}

type leaderElectionClient struct {
	cc *grpc.ClientConn
}

func NewLeaderElectionClient(cc *grpc.ClientConn) LeaderElectionClient {
	return &leaderElectionClient{cc}
}

func (c *leaderElectionClient) RequestVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResult, error) {
	out := new(VoteResult)
	err := grpc.Invoke(ctx, "/rproto.LeaderElection/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionClient) AppendEntry(ctx context.Context, in *AppendEntryRequest, opts ...grpc.CallOption) (*AppendEntryResult, error) {
	out := new(AppendEntryResult)
	err := grpc.Invoke(ctx, "/rproto.LeaderElection/AppendEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LeaderElection service

type LeaderElectionServer interface {
	RequestVote(context.Context, *VoteRequest) (*VoteResult, error)
	AppendEntry(context.Context, *AppendEntryRequest) (*AppendEntryResult, error)
}

func RegisterLeaderElectionServer(s *grpc.Server, srv LeaderElectionServer) {
	s.RegisterService(&_LeaderElection_serviceDesc, srv)
}

func _LeaderElection_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rproto.LeaderElection/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServer).RequestVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElection_AppendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServer).AppendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rproto.LeaderElection/AppendEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServer).AppendEntry(ctx, req.(*AppendEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeaderElection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rproto.LeaderElection",
	HandlerType: (*LeaderElectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _LeaderElection_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntry",
			Handler:    _LeaderElection_AppendEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leader_election.proto",
}

func init() { proto.RegisterFile("leader_election.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0x2c, 0xab, 0x4c, 0x54, 0x70, 0x44, 0xa8, 0x3d, 0xad, 0x39, 0xf5, 0xd4, 0x83,
	0x5e, 0xbc, 0x2e, 0xba, 0x8a, 0xe0, 0xa9, 0x07, 0xaf, 0x25, 0x26, 0x83, 0x14, 0x6a, 0x52, 0x93,
	0xa9, 0xe0, 0xdf, 0xf0, 0x17, 0x4b, 0x93, 0xae, 0xec, 0xa2, 0xeb, 0x29, 0x99, 0x37, 0xc3, 0x7b,
	0x33, 0x1f, 0x9c, 0x77, 0xa4, 0x0c, 0xf9, 0x86, 0x3a, 0xd2, 0xdc, 0x3a, 0x5b, 0xf5, 0xde, 0xb1,
	0xc3, 0xb9, 0x8f, 0xaf, 0xbc, 0x03, 0xf1, 0xec, 0x98, 0x6a, 0x7a, 0x1f, 0x28, 0x30, 0x22, 0xcc,
	0x98, 0xfc, 0x5b, 0x9e, 0x2d, 0xb2, 0x72, 0x56, 0xc7, 0x3f, 0x5e, 0xc2, 0x91, 0x56, 0xd6, 0xb4,
	0x46, 0x31, 0x35, 0xad, 0xc9, 0xf7, 0x17, 0x59, 0x79, 0x5c, 0x8b, 0x1f, 0xed, 0xd1, 0xc8, 0x5b,
	0x80, 0xe4, 0x12, 0x86, 0x6e, 0xa7, 0xc9, 0x87, 0x63, 0x6a, 0x5e, 0xbd, 0xb2, 0x4c, 0xc9, 0xe4,
	0xb0, 0x16, 0xa3, 0xf6, 0x90, 0x24, 0x59, 0x02, 0x2e, 0xfb, 0x9e, 0xac, 0x59, 0x59, 0xf6, 0x9f,
	0xff, 0x6c, 0x24, 0x97, 0x70, 0xba, 0x35, 0xb9, 0x33, 0x35, 0x87, 0x83, 0x30, 0x68, 0x4d, 0x21,
	0x4c, 0x81, 0xeb, 0xf2, 0xea, 0x2b, 0x83, 0x93, 0xa7, 0x48, 0x66, 0x35, 0x81, 0xc1, 0x1b, 0x10,
	0x53, 0xe8, 0x78, 0x0b, 0x9e, 0x55, 0x09, 0x51, 0xb5, 0xc1, 0xa7, 0xc0, 0x6d, 0x71, 0x0c, 0x96,
	0x7b, 0x78, 0x0f, 0x62, 0x63, 0x1f, 0x2c, 0xd6, 0x43, 0xbf, 0xcf, 0x29, 0x2e, 0xfe, 0xec, 0x25,
	0x9f, 0x97, 0x79, 0x6c, 0x5d, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xf2, 0xa8, 0x7e, 0xb4,
	0x01, 0x00, 0x00,
}
